"""empty message

Revision ID: 208dee4a5dc0
Revises: 559e41f937fc
Create Date: 2024-08-17 11:16:06.208268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '208dee4a5dc0'
down_revision: Union[str, None] = '559e41f937fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_index('ix_options_id', table_name='options')
    op.drop_table('options')
    op.drop_constraint('parlay_types_outcome_fkey', 'parlay_types', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('parlay_types_outcome_fkey', 'parlay_types', 'options', ['outcome'], ['id'])
    op.create_table('options',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('option', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='options_pkey')
    )
    op.create_index('ix_options_id', 'options', ['id'], unique=False)
    # ### end Alembic commands ###
