"""empty message

Revision ID: 559e41f937fc
Revises: 89b829f2c23f
Create Date: 2024-08-17 09:57:58.693629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '559e41f937fc'
down_revision: Union[str, None] = '89b829f2c23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('option', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_options_id'), 'options', ['id'], unique=False)
    op.create_table('parlay_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('outcome', sa.Integer(), nullable=True),
    sa.Column('spread', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['outcome'], ['options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parlay_types_id'), 'parlay_types', ['id'], unique=False)
    op.create_table('parlays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type'], ['parlay_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parlays_id'), 'parlays', ['id'], unique=False)
    op.create_table('parlay_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parlay_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parlay_id'], ['parlays.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parlay_teams_id'), 'parlay_teams', ['id'], unique=False)
    op.create_table('parlay_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parlay_id', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parlay_id'], ['parlays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parlay_weeks_id'), 'parlay_weeks', ['id'], unique=False)
    op.create_table('parlay_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parlay_team_id', sa.Integer(), nullable=True),
    sa.Column('parlay_week_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('is_home_team', sa.Boolean(), nullable=False),
    sa.Column('rival_team', sa.String(), nullable=False),
    sa.Column('odds', sa.Integer(), nullable=False),
    sa.Column('spread', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.String(), nullable=True),
    sa.Column('outcome', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parlay_team_id'], ['parlay_teams.id'], ),
    sa.ForeignKeyConstraint(['parlay_week_id'], ['parlay_weeks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parlay_events_id'), 'parlay_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parlay_events_id'), table_name='parlay_events')
    op.drop_table('parlay_events')
    op.drop_index(op.f('ix_parlay_weeks_id'), table_name='parlay_weeks')
    op.drop_table('parlay_weeks')
    op.drop_index(op.f('ix_parlay_teams_id'), table_name='parlay_teams')
    op.drop_table('parlay_teams')
    op.drop_index(op.f('ix_parlays_id'), table_name='parlays')
    op.drop_table('parlays')
    op.drop_index(op.f('ix_parlay_types_id'), table_name='parlay_types')
    op.drop_table('parlay_types')
    op.drop_index(op.f('ix_options_id'), table_name='options')
    op.drop_table('options')
    # ### end Alembic commands ###
